# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreType', models.CharField(choices=[('A', 'Automatic'), ('R', 'Reported')], default='R', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('periodHours', models.IntegerField(default=168)),
                ('status', models.CharField(choices=[('D', 'Done'), ('U', 'Unimportant'), ('N', 'Needs Doing'), ('I', 'Important!'), ('V', 'Very Urgent!!!')], default='D', max_length=1)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoresList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='choresList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorus.ChoresList'),
        ),
    ]
